### ISSUE TITLE
ERROR about pitch_rate_limit!, ROLL RATE LIMIT! and FULL THRUST

### ISSUE THREAD

**Issue by curious-energy** [ZJU-FAST-Lab/Fast-Racing#11]
![Screenshot from 2022-12-07 16-39-25](https://user-images.githubusercontent.com/28819684/206130903-7635e8f4-1d21-4255-9c1f-0eab709fbac7.png)

I use CPU and GPU way to compile this code, something is right, but the drone is lost control! Could you help me.

**Comment by ZhanyuGuo** [comment]
I encountered the same problem too. Have you solved it? @curious-energy Thank you!

**Comment by curious-energy** [comment]
@ZhanyuGuo I tune the parameters full_thrust in the path ~/fast_ws/src/Fast-Racing/src/Ctrl/config/ctrl_param_fpv.yaml, I fix it to 77, all is right!

![racing_zju](https://user-images.githubusercontent.com/28819684/235299275-337e168d-290f-47c0-9eb0-e232d25dd755.png)

**Comment by ZhanyuGuo** [comment]
Not work for me :sob: ... The drone is still lost control.

**Comment by ZhanyuGuo** [comment]
Solved in #12.

**Comment by curious-energy** [comment]
Thank you for your reply, Have a good day!
