### ISSUE TITLE
The Drone Loses Control

### ISSUE THREAD

**Issue by ZhanyuGuo** [ZJU-FAST-Lab/Fast-Racing#12]
# The Drone Loses Control

Hello, thanks for sharing your great work!

Currently, I encountered the same problem as #11, but I can not solve by his way.

## Platform

Ubuntu 20, ROS Noetic.

## Screenshots

![Screenshot from 2023-05-05 14-41-31](https://user-images.githubusercontent.com/65705518/236393161-9f8989b3-ae47-4d7d-838e-7a148b17cf10.png)

![Screenshot from 2023-05-05 14-42-34](https://user-images.githubusercontent.com/65705518/236393214-0d596955-9b90-4d2d-bcbf-4c7c9ba2d3eb.png)

Sorry to bother you.

**Comment by Curry2Puff** [comment]
> 

I also encountered the same problem, how did you solve this problem？

**Comment by ZhanyuGuo** [comment]
> > 
> 
> I also encountered the same problem, how did you solve this problem？

Not yet. :sob:

**Comment by Curry2Puff** [comment]
您好，您的邮件我已收到，祝进一切顺利，谢谢~

**Comment by ZhanyuGuo** [comment]
The issue is solved. I change the `ctrl_rate` in `src/Ctrl/config/ctrl_param_fpv.yaml` from `100.0` to `20.0`, and then it works. :sob:

**Comment by Curry2Puff** [comment]
您好，您的邮件我已收到，祝进一切顺利，谢谢~
