### ISSUE TITLE
RVIZ has blank display

### ISSUE THREAD

**Issue by t-thanh** [ZJU-FAST-Lab/Fast-Racing#2]
Hi, 

I followed your instruction and tested with the Zhangjiajie environment. It work - at least with the AirSim environment (finished all the gates successfully. However, Rviz has one issues. it is blank (no map is displayed)

and I get this warning:
`[ WARN] [1630074867.684464842]: Invalid argument "/world_enu" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like:`

Could you please check if tf2 frames is setup correctly?

Best regards,

**Comment by Leon-Redfield** [comment]
> Hi,
> 
> I followed your instruction and tested with the Zhangjiajie environment. It work - at least with the AirSim environment (finished all the gates successfully. However, Rviz has one issues. it is blank (no map is displayed)
> 
> and I get this warning:
> `[ WARN] [1630074867.684464842]: Invalid argument "/world_enu" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like:`
> 
> Could you please check if tf2 frames is setup correctly?
> 
> Best regards,

Hi! Search for all "/world_enu" and replace them with "world_enu". I guess you are using ubuntu20, and it is required to get rid of the "/" in tf frame_ids.

**Comment by sotpapathe** [comment]
This can be done easily with the following command (provided you have GNU or busybox `sed`):
``` sh
sed -i '/\/world_enu/ s|/world_enu|world_enu|g' $(git grep -l '/world_enu')
```

**Comment by cheslee-z** [comment]
> I am using ubuntu20, but after I replaced all "/world_enu" with "world_enu", I got this error:
``[ERROR] [1664624785.874747168]: wrong map frame id!

**Comment by haoxinnihao** [comment]
@cheslee-z I also have this problem. Do you solve it?

**Comment by xxyLA** [comment]
> @cheslee-z I also have this problem. Do you solve it?

same problem

**Comment by xxyLA** [comment]
> @cheslee-z I also have this problem. Do you solve it?

Recompile
