### ISSUE TITLE
 CMake Error at utils/uav_simulator/Utils/uav_utils

### ISSUE THREAD

**Issue by YUJX19** [ZJU-FAST-Lab/Fast-Racing#4]
When compiling the repo, I encounter an error, such as

> CMake Error at utils/uav_simulator/Utils/uav_utils/CMakeLists.txt:31 (find_package):
>   By not providing "FindEigen.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Eigen", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Eigen" with any of
>   the following names:
> 
>     EigenConfig.cmake
>     eigen-config.cmake

But I type `sudo gedit /usr/include/eigen3/Eigen/src/Core/util/Macros.h` in the terminal, and find the version is 3.3.4. 

Meanwhile, I find the _ego-planner_ repo also has a file _uav_utils/CMakeLists.txt_ same to _Fast-Racing_, and I can successfully compile _ego-planner_, but _Fast-Racing_ not. 
I need help. Thanks!

**Comment by Han-Sin** [comment]
If you can successfully complie _ego-planner_, you can just replace /utils/uav_simulator/uav_tils package in this repo with the one in _ego-planner_.  In theory, this will not affect the operation

**Comment by YUJX19** [comment]
Thank you very much~~
When I successfully solved the errors in ego-planner, the project also ran corrected.
