### ISSUE TITLE
Some questions about controller

### ISSUE THREAD

**Issue by dssdyx** [ZJU-FAST-Lab/Fast-Racing#5]
1. What's the difference between using desired [roll,pitch](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/blob/949bc1b2b3db1486729f32d3ba73fbca863fecac/onboard_computer/controller/n3ctrl/src/controller.cpp#L305-L306) and using desired [body rate](https://github.com/ZJU-FAST-Lab/Fast-Racing/blob/main/src/Ctrl/src/controller.cpp#L541-L544) to control FCU?
2. Are there any tips for helping tune PID?
3. In Airsim, it's simple flight mode without FCU SITL and just using pv controller. Do you want to use real FCU in SITL or HITL for se3 controller in the future?

**Comment by Han-Sin** [comment]
1.Bodyrate mode will use the desired jerk as the feedfoward which can make the controller more accurate and agile. 
2.Interesting question. I always tune the parameters by observing the step response curve. 
3.Yes, we are doing this now~

**Comment by dssdyx** [comment]
> 1.Bodyrate mode will use the desired jerk as the feedfoward which can make the controller more accurate and agile. 2.Interesting question. I always tune the parameters by observing the step response curve. 3.Yes, we are doing this now~

Thank you for your answers.That's very helpful.
